// DO NOT EDIT. This file is generated by Fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import * as $0 from "./routes/EpisodeVotingPage.tsx";
import * as $1 from "./routes/_404.tsx";
import * as $2 from "./routes/_app.tsx";
import * as $3 from "./routes/api/[episode].ts";
import * as $4 from "./routes/index.tsx";
import * as $$0 from "./islands/Card.tsx";
import * as $$1 from "./islands/InfoCard.tsx";
import * as $$2 from "./islands/Nav.tsx";
import * as $$3 from "./islands/Picker.tsx";
import * as $$4 from "./islands/SetterButton.tsx";

const manifest = {
  routes: {
    "./routes/EpisodeVotingPage.tsx": $0,
    "./routes/_404.tsx": $1,
    "./routes/_app.tsx": $2,
    "./routes/api/[episode].ts": $3,
    "./routes/index.tsx": $4,
  },
  islands: {
    "./islands/Card.tsx": $$0,
    "./islands/InfoCard.tsx": $$1,
    "./islands/Nav.tsx": $$2,
    "./islands/Picker.tsx": $$3,
    "./islands/SetterButton.tsx": $$4,
  },
  baseUrl: import.meta.url,
};

export default manifest;
