type Episode = {
  number: number;
  title: string;
  imageUrl: string
};

export type EpisodeList = Episode[];

export const episodes: EpisodeList = [
  // Season 1
  { number: 1, title: "Space Pilot 3000", imageUrl: "./images/episodes/Space_Pilot_3000.webp" },
  { number: 2, title: "The Series Has Landed", imageUrl: "./images/episodes/The_Series_Has_Landed.webp" },
  { number: 3, title: "I, Roommate", imageUrl: "./images/episodes/I_Roomate.webp" },
  { number: 4, title: "Love's Labours Lost in Space", imageUrl: "./images/episodes/Loves_Labours_Lost_In_Space.webp" },
  { number: 5, title: "Fear of a Bot Planet", imageUrl: "./images/episodes/Fear_of_a_Bot_Planet.webp" },
  { number: 6, title: "A Fishful of Dollars", imageUrl: "./images/episodes/A_Fishful_of_Dollars.webp" },
  { number: 7, title: "My Three Suns", imageUrl: "./images/episodes/My_Three_Suns.webp" },
  { number: 8, title: "A Big Piece of Garbage", imageUrl: "./images/episodes/A_Big_Piece_of_Garbage.webp" },
  { number: 9, title: "Hell Is Other Robots", imageUrl: "./images/episodes/Hell_Is_Other_Robots.webp" },
  { number: 10, title: "A Flight to Remember", imageUrl: "./images/episodes/A_Flight_to_Remember.webp"},
  { number: 11, title: "Mars University", imageUrl: "./images/episodes/Mars_University.webp"},
  { number: 12, title: "When Aliens Attack", imageUrl: "./images/episodes/When_Aliens_Attack.webp"},
  { number: 13, title: "Fry & the Slurm Factory", imageUrl: "./images/episodes/Fry_and_The_Slurm_Factory.webp"},
  // Season 2
  { number: 14, title: "I Second That Emotion", imageUrl: "./images/episodes/I_Second_That_Emotion.webp" },
  { number: 15, title: "Brannigan, Begin Again", imageUrl: "./images/episodes/Brannigan_Begin_Again.webp" },
  { number: 16, title: "A Head in the Polls", imageUrl: "./images/episodes/A_Head_in_the_Polls.webp" },
  { number: 17, title: "Xmas Story", imageUrl: "./images/episodes/Xmas_Story.webp" },
  { number: 18, title: "Why Must I Be a Crustacean in Love?", imageUrl: "./images/episodes/Why_Must_I_Be_a_Crustacean_in_Love.webp" },
  { number: 19, title: "The Lesser of Two Evils", imageUrl: "./images/episodes/The_Lesser_of_Two_Evils.webp" },
  { number: 20, title: "Put Your Head on My Shoulders", imageUrl: "./images/episodes/Put_Your_Head_on_My_Shoulders.webp" },
  { number: 21, title: "Raging Bender", imageUrl: "./images/episodes/Raging_Bender.webp" },
  { number: 22, title: "A Bicyclops Built for Two", imageUrl: "./images/episodes/A_Bicyclops_Built_for_Two.webp" },
  { number: 23, title: "A Clone of My Own", imageUrl: "./images/episodes/A_Clone_of_My_Own.webp" },
  { number: 24, title: "How Hermes Requisitioned His Groove Back", imageUrl: "./images/episodes/How_Hermes_Requisitioned_His_Groove_Back.webp" },
  { number: 25, title: "The Deep South", imageUrl: "./images/episodes/The_Deep_South.webp" },
  { number: 26, title: "Bender Gets Made", imageUrl: "./images/episodes/Bender_Gets_Made.webp" },
  { number: 27, title: "Mother's Day", imageUrl: "./images/episodes/Mother's_Day.webp" },
  { number: 28, title: "The Problem with Popplers", imageUrl: "./images/episodes/The_Problem_with_Popplers.webp" },
  { number: 29, title: "Anthology of Interest I", imageUrl: "./images/episodes/Anthology_of_Interest_One.webp" },
  { number: 30, title: "War is the H-Word", imageUrl: "./images/episodes/War_Is_The_H-Word.webp" },
  { number: 31, title: "The Honking", imageUrl: "./images/episodes/The_Honking.webp" },
  { number: 32, title: "The Cryonic Woman", imageUrl: "./images/episodes/The_Cryonic_Woman.webp" },
  // Season 3
  { number: 33, title: "Amazon Women in the Mood", imageUrl: "./images/episodes/Amazon_Women_in_the_Mood.webp" },
  { number: 34, title: "Parasites Lost", imageUrl: "./images/episodes/Parasites_Lost.webp" },
  { number: 35, title: "A Tale of Two Santas", imageUrl: "./images/episodes/A_Tale_of_Two_Santas.webp" },
  { number: 36, title: "The Luck of the Fryrish", imageUrl: "./images/episodes/The_Luck_of_the_Fryrish.webp" },
  { number: 37, title: "The Birdbot of Ice-Catraz", imageUrl: "./images/episodes/Bird-bot_of_Ice_Catraz.webp" },
  { number: 38, title: "Bendless Love", imageUrl: "./images/episodes/Bendless_Love.webp" },
  { number: 39, title: "The Day the Earth Stood Stupid", imageUrl: "./images/episodes/The_Day_the_Earth_Stood_Stupid.webp" },
  { number: 40, title: "That's Lobstertainment!", imageUrl: "./images/episodes/That's_Lobstertainment!.webp" },
  { number: 41, title: "The Cyber House Rules", imageUrl: "./images/episodes/The_Cyber_House_Rules.webp" },
  { number: 42, title: "Where the Buggalo Roam", imageUrl: "./images/episodes/Where_the_Buggalo_Roam.webp" },
  { number: 43, title: "Insane in the Mainframe", imageUrl: "./images/episodes/Insane_in_the_Mainframe.webp" },
  { number: 44, title: "The Route of All Evil", imageUrl: "./images/episodes/The_Route_of_All_Evil.webp" },
  { number: 45, title: "Bendin' in the Wind", imageUrl: "./images/episodes/Bendin_in_the_Wind.webp" },
  { number: 46, title: "Time Keeps on Slippin'", imageUrl: "./images/episodes/" },
  { number: 47, title: "I Dated a Robot", imageUrl: "./images/episodes/" },
  { number: 48, title: "A Leela of Her Own", imageUrl: "./images/episodes/" },
  { number: 49, title: "A Pharaoh to Remember", imageUrl: "./images/episodes/" },
  { number: 50, title: "Anthology of Interest II", imageUrl: "./images/episodes/" },
  { number: 51, title: "Roswell That Ends Well", imageUrl: "./images/episodes/" },
  { number: 52, title: "Godfellas", imageUrl: "" },
  { number: 53, title: "Future Stock", imageUrl: "" },
  { number: 54, title: "A Clone of My Own", imageUrl: "" },
  // Season 4
  { number: 55, title: "Kif Gets Knocked Up a Notch", imageUrl: "" },
  { number: 56, title: "Leela's Homeworld", imageUrl: "" },
  { number: 57, title: "Love and Rocket", imageUrl: "" },
  { number: 58, title: "Less Than Hero", imageUrl: "" },
  { number: 59, title: "A Taste of Freedom", imageUrl: "" },
  { number: 60, title: "Bender Should Not Be Allowed on Television", imageUrl: "" },
  { number: 61, title: "Jurassic Bark", imageUrl: "" },
  { number: 62, title: "Crimes of the Hot", imageUrl: "" },
  { number: 63, title: "Teenage Mutant Leela's Hurdles", imageUrl: "" },
  { number: 64, title: "The Why of Fry", imageUrl: "" },
  { number: 65, title: "Where No Fan Has Gone Before", imageUrl: "" },
  { number: 66, title: "The Sting", imageUrl: "" },
  { number: 67, title: "Bend Her", imageUrl: "" },
  { number: 68, title: "Obsoletely Fabulous", imageUrl: "" },
  { number: 69, title: "The Farnsworth Parabox", imageUrl: "" },
  { number: 70, title: "Three Hundred Big Boys", imageUrl: "" },
  { number: 71, title: "Spanish Fry", imageUrl: "" },
  { number: 72, title: "The Devil's Hands Are Idle Playthings", imageUrl: "" },
  // Season 6
  { number: 73, title: "Rebirth", imageUrl: "" },
  { number: 74, title: "In-A-Gadda-Da-Leela", imageUrl: "" },
  { number: 75, title: "Attack of the Killer App", imageUrl: "" },
  { number: 76, title: "Proposition Infinity", imageUrl: "" },
  { number: 77, title: "The Duh-Vinci Code", imageUrl: "" },
  { number: 78, title: "Lethal Inspection", imageUrl: "" },
  { number: 79, title: "The Late Philip J. Fry", imageUrl: "" },
  { number: 80, title: "That Darn Katz!", imageUrl: "" },
  { number: 81, title: "A Clockwork Origin", imageUrl: "" },
  { number: 82, title: "The Prisoner of Benda", imageUrl: "" },
  { number: 83, title: "Lrrreconcilable Ndndifferences", imageUrl: "" },
  { number: 84, title: "The Mutants Are Revolting", imageUrl: "" },
  { number: 85, title: "The Futurama Holiday Spectacular", imageUrl: "" },
  { number: 86, title: "Neutopia", imageUrl: "" },
  { number: 87, title: "Benderama", imageUrl: "" },
  { number: 88, title: "Ghost in the Machines", imageUrl: "" },
  { number: 89, title: "Law and Oracle", imageUrl: "" },
  { number: 90, title: "The Silence of the Clamps", imageUrl: "" },
  { number: 91, title: "Yo Leela Leela", imageUrl: "" },
  { number: 92, title: "All the Presidents' Heads", imageUrl: "" },
  { number: 93, title: "Möbius Dick", imageUrl: "" },
  { number: 94, title: "Fry Am the Egg Man", imageUrl: "" },
  { number: 95, title: "The Tip of the Zoidberg", imageUrl: "" },
  { number: 96, title: "Cold Warriors", imageUrl: "" },
  { number: 97, title: "Overclockwise", imageUrl: "" },
  { number: 98, title: "Reincarnation", imageUrl: "" },
  // Season 7
  { number: 99, title: "The Bots and the Bees", imageUrl: "" },
  { number: 100, title: "A Farewell to Arms", imageUrl: "" },
  { number: 101, title: "Decision 3012", imageUrl: "" },
  { number: 102, title: "The Thief of Baghead", imageUrl: "" },
  { number: 103, title: "Zapp Dingbat", imageUrl: "" },
  { number: 104, title: "The Butterjunk Effect", imageUrl: "" },
  { number: 105, title: "The Six Million Dollar Mon", imageUrl: "" },
  { number: 106, title: "Fun on a Bun", imageUrl: "" },
  { number: 107, title: "Free Will Hunting", imageUrl: "" },
  { number: 108, title: "Near-Death Wish", imageUrl: "" },
  { number: 109, title: "31st Century Fox", imageUrl: "" },
  { number: 110, title: "Viva Mars Vegas", imageUrl: "" },
  { number: 111, title: "Naturama", imageUrl: "" },
  { number: 112, title: "Forty Percent Leadbelly", imageUrl: "" },
  { number: 113, title: "2-D Blacktop", imageUrl: "" },
  { number: 114, title: "T.: The Terrestrial", imageUrl: "" },
  { number: 115, title: "Fry and Leela's Big Fling", imageUrl: "" },
  { number: 116, title: "The Inhuman Torch", imageUrl: "" },
  { number: 117, title: "Saturday Morning Fun Pit", imageUrl: "" },
  { number: 118, title: "Calculon 2.0", imageUrl: "" },
  { number: 119, title: "The Assie Come Home", imageUrl: "" },
  { number: 120, title: "Leela and the Genestalk", imageUrl: "" },
  { number: 121, title: "Game of Tones", imageUrl: "" },
  { number: 122, title: "Murder on the Planet Express", imageUrl: "" },
  { number: 123, title: "Stench and Stenchibility", imageUrl: "" },
  { number: 124, title: "Meanwhile", imageUrl: "" }
];
