
type Episode = {
  number: number;
  title: string;
};

export type EpisodeList = Episode[];

export const episodes: EpisodeList = [
  // Season 1
  { number: 1, title: "Space Pilot 3000" },
  { number: 2, title: "The Series Has Landed" },
  { number: 3, title: "I, Roommate" },
  { number: 4, title: "Love's Labours Lost in Space" },
  { number: 5, title: "Fear of a Bot Planet" },
  { number: 6, title: "A Fishful of Dollars" },
  { number: 7, title: "My Three Suns" },
  { number: 8, title: "A Big Piece of Garbage" },
  { number: 9, title: "Hell Is Other Robots" },
  // Season 2
  { number: 10, title: "I Second That Emotion" },
  { number: 11, title: "Brannigan, Begin Again" },
  { number: 12, title: "A Head in the Polls" },
  { number: 13, title: "Xmas Story" },
  { number: 14, title: "Why Must I Be a Crustacean in Love?" },
  { number: 15, title: "The Lesser of Two Evils" },
  { number: 16, title: "Put Your Head on My Shoulders" },
  { number: 17, title: "Raging Bender" },
  { number: 18, title: "A Bicyclops Built for Two" },
  { number: 19, title: "A Clone of My Own" },
  { number: 20, title: "How Hermes Requisitioned His Groove Back" },
  { number: 21, title: "The Deep South" },
  { number: 22, title: "Bender Gets Made" },
  { number: 23, title: "Mother's Day" },
  { number: 24, title: "The Problem with Popplers" },
  { number: 25, title: "Anthology of Interest I" },
  { number: 26, title: "War is the H-Word" },
  { number: 27, title: "The Honking" },
  { number: 28, title: "The Cryonic Woman" },
  // Season 3
  { number: 29, title: "Amazon Women in the Mood" },
  { number: 30, title: "Parasites Lost" },
  { number: 31, title: "A Tale of Two Santas" },
  { number: 32, title: "The Luck of the Fryrish" },
  { number: 33, title: "The Birdbot of Ice-Catraz" },
  { number: 34, title: "Bendless Love" },
  { number: 35, title: "The Day the Earth Stood Stupid" },
  { number: 36, title: "That's Lobstertainment!" },
  { number: 37, title: "The Cyber House Rules" },
  { number: 38, title: "Where the Buggalo Roam" },
  { number: 39, title: "Insane in the Mainframe" },
  { number: 40, title: "The Route of All Evil" },
  { number: 41, title: "Bendin' in the Wind" },
  { number: 42, title: "Time Keeps on Slippin'" },
  { number: 43, title: "I Dated a Robot" },
  { number: 44, title: "A Leela of Her Own" },
  { number: 45, title: "A Pharaoh to Remember" },
  { number: 46, title: "Anthology of Interest II" },
  { number: 47, title: "Roswell That Ends Well" },
  { number: 48, title: "Godfellas" },
  { number: 49, title: "Future Stock" },
  { number: 50, title: "A Clone of My Own" },
  // Season 4
  { number: 51, title: "Kif Gets Knocked Up a Notch" },
  { number: 52, title: "Leela's Homeworld" },
  { number: 53, title: "Love and Rocket" },
  { number: 54, title: "Less Than Hero" },
  { number: 55, title: "A Taste of Freedom" },
  { number: 56, title: "Bender Should Not Be Allowed on Television" },
  { number: 57, title: "Jurassic Bark" },
  { number: 58, title: "Crimes of the Hot" },
  { number: 59, title: "Teenage Mutant Leela's Hurdles" },
  { number: 60, title: "The Why of Fry" },
  { number: 61, title: "Where No Fan Has Gone Before" },
  { number: 62, title: "The Sting" },
  { number: 63, title: "Bend Her" },
  { number: 64, title: "Obsoletely Fabulous" },
  { number: 65, title: "The Farnsworth Parabox" },
  { number: 66, title: "Three Hundred Big Boys" },
  { number: 67, title: "Spanish Fry" },
  { number: 68, title: "The Devil's Hands Are Idle Playthings" },
  // Season 6
  { number: 69, title: "Rebirth" },
  { number: 70, title: "In-A-Gadda-Da-Leela" },
  { number: 71, title: "Attack of the Killer App" },
  { number: 72, title: "Proposition Infinity" },
  { number: 73, title: "The Duh-Vinci Code" },
  { number: 74, title: "Lethal Inspection" },
  { number: 75, title: "The Late Philip J. Fry" },
  { number: 76, title: "That Darn Katz!" },
  { number: 77, title: "A Clockwork Origin" },
  { number: 78, title: "The Prisoner of Benda" },
  { number: 79, title: "Lrrreconcilable Ndndifferences" },
  { number: 80, title: "The Mutants Are Revolting" },
  { number: 81, title: "The Futurama Holiday Spectacular" },
  { number: 82, title: "Neutopia" },
  { number: 83, title: "Benderama" },
  { number: 84, title: "Ghost in the Machines" },
  { number: 85, title: "Law and Oracle" },
  { number: 86, title: "The Silence of the Clamps" },
  { number: 87, title: "Yo Leela Leela" },
  { number: 88, title: "All the Presidents' Heads" },
  { number: 89, title: "Möbius Dick" },
  { number: 90, title: "Fry Am the Egg Man" },
  { number: 91, title: "The Tip of the Zoidberg" },
  { number: 92, title: "Cold Warriors" },
  { number: 93, title: "Overclockwise" },
  { number: 94, title: "Reincarnation" },
  // Season 7
  { number: 95, title: "The Bots and the Bees" },
  { number: 96, title: "A Farewell to Arms" },
  { number: 97, title: "Decision 3012" },
  { number: 98, title: "The Thief of Baghead" },
  { number: 99, title: "Zapp Dingbat" },
  { number: 100, title: "The Butterjunk Effect" },
  { number: 101, title: "The Six Million Dollar Mon" },
  { number: 102, title: "Fun on a Bun" },
  { number: 103, title: "Free Will Hunting" },
  { number: 104, title: "Near-Death Wish" },
  { number: 105, title: "31st Century Fox" },
  { number: 106, title: "Viva Mars Vegas" },
  { number: 107, title: "Naturama" },
  { number: 108, title: "Forty Percent Leadbelly" },
  { number: 109, title: "2-D Blacktop" },
  { number: 110, title: "T.: The Terrestrial" },
  { number: 111, title: "Fry and Leela's Big Fling" },
  { number: 112, title: "The Inhuman Torch" },
  { number: 113, title: "Saturday Morning Fun Pit" },
  { number: 114, title: "Calculon 2.0" },
  { number: 115, title: "Assie Come Home" },
  { number: 116, title: "Leela and the Genestalk" },
  { number: 117, title: "Game of Tones" },
  { number: 118, title: "Murder on the Planet Express" },
  { number: 119, title: "Stench and Stenchibility" },
  { number: 120, title: "Meanwhile" }
];